import {ProductMidd} from '../server/Classes/GenericMiddleware.js'
import * as store from './helperTest/testStore.js'
import * as help from './helperTest/02-helpdata.js'
import {redirectionImages } from './helperTest/imageServices.js'
import {Landing} from '../server/database.js'